[package]
name = "bootcamp"
version = "0.1.0"
edition = "2021"
description = "LGR Bootcamp"
license = "MIT"

# See more at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0"
uuid = { version = "1.8", features = ["v4"] }
