[package]
name = "learning_axum"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["macros"] }
tokio = { version = "1.22.0", features = ["full"] }
serde = { version = "1.0.229", features = ["derive"] }
rand = "0.10.3"
tower-http = { version = "0.7.1", features = ["trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23" , features = ["env-filter"]}

# configuration
config = "0.15.27"

# database
sqlx = { version = "0.8.6", features = ["runtime-tokio", "tls-rustls", "postgres", "macros"] }

# environment variables
dotenvy = "0.15.7"