INSERT INTO zettels (content) VALUES ('Good.');
INSERT INTO zettels (content) VALUES ('No one should be honored for doing what is expected.');
INSERT INTO zettels (content) VALUES ('He was a normal person of ordinary birth with an ordinary lifestyle and no particular talent. Yet through sheer effort, he forced open his limits and demolished his limiter.');
INSERT INTO zettels (content) VALUES ('Looks like you forgot, once again, how powerful you are.');
INSERT INTO zettels (content) VALUES ('How you do anything is how you do everything.');
INSERT INTO zettels (content) VALUES ('Whenever I get to a low point where I think: Why do I even bother?. I just remind myself: this is where most of people stop and this is why they don''t win. Go one more.');
INSERT INTO zettels (content) VALUES ('If you''re going through hell, keep going. Why would you stop in hell?');
INSERT INTO zettels (content) VALUES ('If everything around you seems dark, look again, you might be the light.');
INSERT INTO zettels (content) VALUES ('A man cannot master the path he is walking if he only looks for the end result. He must take the time to delve deeply into the reason he has chosen that path.');
INSERT INTO zettels (content) VALUES ('A ship is always safe at the shore, but that''s not what it''s built for.');
INSERT INTO zettels (content) VALUES ('I''m glad God ruined my plans. His ended up way better than mine.');
INSERT INTO zettels (content) VALUES ('A man crawling in confusion moves further than one frozen in doubt.');
INSERT INTO zettels (content) VALUES ('When the thoughts get too big, go to somewhere you feel small.');
INSERT INTO zettels (content) VALUES ('It is not bad to celebrate a simple life -- Bilbo Baggins.');
INSERT INTO zettels (content) VALUES ('Failure only breaks those who expect success without effort.');
INSERT INTO zettels (content) VALUES ('Your wounds is the place where the light enters you.');
INSERT INTO zettels (content) VALUES ('A man who fears pain more than failure will taste both.');
INSERT INTO zettels (content) VALUES ('Do all that you can do. And when you''ve done all you can do and hell still comes to breakfast... let it finish out, then pick up the pieces, learn from it, and start over.');
INSERT INTO zettels (content) VALUES ('People are people. None of it is intentional. Never attribute to malice what can be attributed to incompetence. It''s far more likely that they''re all in their own worlds doing their own things. They are not paying attention to the world around them.');
INSERT INTO zettels (content) VALUES ('Do more than belong, participate. Do more than care, help. Do more than believe, practice. Do more than being fair, be kind. Do more than forgive, forget. Do more than dream, work.');
INSERT INTO zettels (content) VALUES ('The true measure of a man isn''t what he reveals to the world, but what he hides from it.');
INSERT INTO zettels (content) VALUES ('Feeling bad after making a decision doesn''t mean it was the wrong decision.');
INSERT INTO zettels (content) VALUES ('If your path demands you to walk through hell, walk as if you owned the place.');
INSERT INTO zettels (content) VALUES ('It''s possible. Imagine you entire mindset was just like it''s possible to get to the next level. It''s possible to be great. It''s possible to get more money. It''s possible to be healthy. Sometimes you have to create a delusion. A delusion that is so far out there that people would think that you are crazy.');
INSERT INTO zettels (content) VALUES ('What if it turns out better than you expected? What if you can trust yourself to be able to handle it? And What if all those things you''ve been dreaming of are actually closer than you might realize?');
INSERT INTO zettels (content) VALUES ('Whenever I get to a low point where I think: ''Why do I even bother''. I just remind myself: this is where most of people stop and this is why they don''t win. Go one more.');
INSERT INTO zettels (content) VALUES ('I learned the hard way not to vent to others. Write down. Throw it out. Tell God. Keep it to yourself.');
INSERT INTO zettels (content) VALUES ('The devil wouldn''t be attacking you so hard if there wasn''t something valuable inside of it. Remember, thieves don''t break into empty homes.');
INSERT INTO zettels (content) VALUES ('Everything feels difficult when you''re about to level up. Don''t quit.');
INSERT INTO zettels (content) VALUES ('Everyday it gets a little easier. But you gotta do it everyday. That''s the hard part.');
INSERT INTO zettels (content) VALUES ('At the end of the day, it''s up to you to make your life better, because, truth be told, no one is willing to jump on a sinking ship.');
INSERT INTO zettels (content) VALUES ('This short time we have now is without a doubt just a break that will lead into our next adventure. Yes. Time to rest one''s bones.');
INSERT INTO zettels (content) VALUES ('Your work was not wasted; it is just being stored.');
INSERT INTO zettels (content) VALUES ('The aggregation of marginal gains, which was the philosophy of searching for a tiny margin of improvement in everything you do.');
INSERT INTO zettels (content) VALUES ('Meaningful change does not require radical change. Small habits can make a meaningful difference by providing evidence of a new identity.');
INSERT INTO zettels (content) VALUES ('Reframing your habits to highlight their benefits rather than their drawbacks is a fast and lightweight way to reprogram your mind and make a habit seem more attractive.');
INSERT INTO zettels (content) VALUES ('Your habits are modern-day solutions to ancient desires.');
INSERT INTO zettels (content) VALUES ('Habits are automatic choices that influence the conscious decisions that follow. A habit can be completed in just a few seconds, but it can also shape the actions that you take for minutes or hours afterward.');
INSERT INTO zettels (content) VALUES ('The last mile is always the least crowded.  Reinforcement ties your habit to an immediate reward, which makes it satisfying when you finish.');
INSERT INTO zettels (content) VALUES ('It''s not possible. No, it''s necessary.');
INSERT INTO zettels (content) VALUES ('The records show efficient behavior operating in hazardous situations. I supplied the tools to maintain that efficiency');