[package]
name = "c4_benchmark_tests"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "sorting_benchmark"
# Disable Rust benchmark feature
harness = false