[package]
name = "c7_error_stack"
version = "0.1.0"
edition = "2021"

[dependencies]
# error-stack
# https://hash.dev/blog/announcing-error-stack

log = { version = "0.4.21"}
env_logger = { version = "0.9.3" }
error-stack = { version = "0.1.1" }