name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  
  beginner_s1:
    name: Beginner > 01. Get Up And Running FAST!
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c1_hello_pod/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c2_variables/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c3_data_types/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c4_constants_statics/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c5_functions/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c6_flow_control/Cargo.toml
    #- name: Run tests
    #  run: cargo test --verbose

  beginner_s2:
    name: Beginner > 02. How Rust Achieves Memory Safety
    runs-on: ubuntu-latest
    needs: beginner_s1
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo run --manifest-path bootcamp/1_beginner/2_memory/c1_ownership/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/2_memory/c2_ownership_continued/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/2_memory/c3_borrowing/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/2_memory/c4_slices/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/2_memory/c5_strings/Cargo.toml

  beginner_s3:
    name: Beginner > 03. Building Your Own Data Types
    runs-on: ubuntu-latest
    needs: beginner_s2
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c1_structs/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c2_implementation_blocks/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c3_tuple_structs/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c4_enums/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c5_matching/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c6_option/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c7_result/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c8_vectors/Cargo.toml
  beginner_s4:
    name: Beginner > 04. How to Structure Your Projects
    runs-on: ubuntu-latest
    needs: beginner_s3
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo build --manifest-path bootcamp/1_beginner/4_projects/c1_structure/Cargo.toml
       cargo build --manifest-path bootcamp/1_beginner/4_projects/c1_structure_lib/Cargo.toml
       cargo build --manifest-path bootcamp/1_beginner/4_projects/c2_modules_part1/Cargo.toml
       cargo build --manifest-path bootcamp/1_beginner/4_projects/c3_modules_part2/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/4_projects/c4_modules_part3/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/4_projects/c5_publishing/Cargo.toml
  beginner_s5:
    name: Beginner > 05. Structuring Larger Projects
    runs-on: ubuntu-latest
    needs: beginner_s4
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo run --manifest-path bootcamp/1_beginner/5_larger_projects/c1_cargo_features/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/5_larger_projects/c2_cargo_workspaces/Cargo.toml