name: Rust

on:
  push:
    branches: [ "main", "feature/tsu-pods" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Beginner > 01. Get Up And Running FAST!
      run: |
       cargo run --manifest-path bootcamp/01_beginner/01_setup_fast/c01_hello_pod/Cargo.toml --verbose
       cargo run --manifest-path bootcamp/01_beginner/01_setup_fast/c02_variables/Cargo.toml --verbose
       cargo run --manifest-path bootcamp/01_beginner/01_setup_fast/c03_data_types/Cargo.toml --verbose
       cargo run --manifest-path bootcamp/01_beginner/01_setup_fast/c04_constants_statics/Cargo.toml --verbose
       cargo run --manifest-path bootcamp/01_beginner/01_setup_fast/c05_functions/Cargo.toml --verbose
       cargo run --manifest-path bootcamp/01_beginner/01_setup_fast/c06_flow_control/Cargo.toml --verbose
    - name: Beginner > 02. How Rust Achieves Memory Safety
      run: |
       cargo run --manifest-path bootcamp/01_beginner/02_memory/c01_ownership/Cargo.toml --verbose
       cargo run --manifest-path bootcamp/01_beginner/02_memory/c02_ownership_continued/Cargo.toml --verbose
    #- name: Run tests
    #  run: cargo test --verbose
