name: Rust

on:
  push:
    branches: [ "main", "feature/tsu-pods" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run
      run: cargo run --manifest-path bootcamp/01_beginner/c01_hello_pod/Cargo.toml --verbose
    #- name: Run tests
    #  run: cargo test --verbose
