name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  
  beginner_s1:
    name: Beginner > 01. Get Up And Running FAST!
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c01_hello_pod/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c02_variables/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c03_data_types/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c04_constants_statics/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c05_functions/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c06_flow_control/Cargo.toml
    #- name: Run tests
    #  run: cargo test --verbose

  beginner_s2:
    name: Beginner > 02. How Rust Achieves Memory Safety
    runs-on: ubuntu-latest
    needs: beginner_s1
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo run --manifest-path bootcamp/1_beginner/2_memory/c01_ownership/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/2_memory/c02_ownership_continued/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/2_memory/c03_borrowing/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/2_memory/c04_slices/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/2_memory/c05_strings/Cargo.toml

  beginner_s3:
    name: Beginner > 03. Building Your Own Data Types
    runs-on: ubuntu-latest
    needs: beginner_s2
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c01_structs/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c02_implementation_blocks/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c03_tuple_structs/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c04_enums/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c05_matching/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c06_option/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c07_result/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c08_vectors/Cargo.toml