name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  
  beginner_s1:
    name: Beginner > 1. Get Up And Running FAST!
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c1_hello_pod/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c2_variables/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c3_data_types/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c4_constants_statics/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c5_functions/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/1_setup_fast/c6_flow_control/Cargo.toml
    #- name: Run tests
    #  run: cargo test --verbose

  beginner_s2:
    name: Beginner > 2. How Rust Achieves Memory Safety
    runs-on: ubuntu-latest
    needs: beginner_s1
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo run --manifest-path bootcamp/1_beginner/2_memory/c1_ownership/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/2_memory/c2_ownership_continued/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/2_memory/c3_borrowing/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/2_memory/c4_slices/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/2_memory/c5_strings/Cargo.toml

  beginner_s3:
    name: Beginner > 3. Building Your Own Data Types
    runs-on: ubuntu-latest
    needs: beginner_s2
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c1_structs/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c2_implementation_blocks/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c3_tuple_structs/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c4_enums/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c5_matching/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c6_option/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c7_result/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/3_own_data_types/c8_vectors/Cargo.toml
  beginner_s4:
    name: Beginner > 4. How to Structure Your Projects
    runs-on: ubuntu-latest
    needs: beginner_s3
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo build --manifest-path bootcamp/1_beginner/4_projects/c1_structure/Cargo.toml
       cargo build --manifest-path bootcamp/1_beginner/4_projects/c1_structure_lib/Cargo.toml
       cargo build --manifest-path bootcamp/1_beginner/4_projects/c2_modules_part1/Cargo.toml
       cargo build --manifest-path bootcamp/1_beginner/4_projects/c3_modules_part2/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/4_projects/c4_modules_part3/Cargo.toml
       cargo run --manifest-path bootcamp/1_beginner/4_projects/c5_publishing/Cargo.toml
  beginner_s5:
    name: Beginner > 5. Structuring Larger Projects
    runs-on: ubuntu-latest
    needs: beginner_s4
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo run --manifest-path bootcamp/1_beginner/5_larger_projects/c1_cargo_features/Cargo.toml
       cargo run --bin blog_api --manifest-path bootcamp/1_beginner/5_larger_projects/c2_cargo_workspaces/Cargo.toml
       cargo run --bin blog_web --manifest-path bootcamp/1_beginner/5_larger_projects/c2_cargo_workspaces/Cargo.toml
  beginner_s6:
    name: Beginner > 6. How To Test & Document Your Code
    runs-on: ubuntu-latest
    needs: beginner_s5
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo test --manifest-path bootcamp/1_beginner/6_test_and_document/c1_unit_tests/Cargo.toml
       cargo test --manifest-path bootcamp/1_beginner/6_test_and_document/c2_integration_tests/Cargo.toml
       cargo test --manifest-path bootcamp/1_beginner/6_test_and_document/c3_documentation/Cargo.toml
       cargo bench --manifest-path bootcamp/1_beginner/6_test_and_document/c4_benchmark_tests/Cargo.toml
  intermediate_s1:
    name: Intermediate > 1. Polymorphism with Generics and Traits
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo run --manifest-path bootcamp/2_intermediate/1_polymorphism/c1_generics/Cargo.toml
       cargo run --manifest-path bootcamp/2_intermediate/1_polymorphism/c2_traits/Cargo.toml
       cargo run --manifest-path bootcamp/2_intermediate/1_polymorphism/c3_trait_bounds/Cargo.toml
       cargo run --manifest-path bootcamp/2_intermediate/1_polymorphism/c4_super_traits/Cargo.toml
       cargo run --manifest-path bootcamp/2_intermediate/1_polymorphism/c5_trait_objects/Cargo.toml
       cargo run --manifest-path bootcamp/2_intermediate/1_polymorphism/c6_deriving_traits/Cargo.toml
       cargo run --manifest-path bootcamp/2_intermediate/1_polymorphism/c7_orphan_rule/Cargo.toml
  intermediate_s2:
    name: Intermediate > 2. Advanced Memory Management
    runs-on: ubuntu-latest
    needs: intermediate_s1
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo run --manifest-path bootcamp/2_intermediate/2_memory_management/c1_concrete_lifetimes/Cargo.toml
       cargo run --manifest-path bootcamp/2_intermediate/2_memory_management/c2_generic_lifetimes/Cargo.toml
       cargo run --manifest-path bootcamp/2_intermediate/2_memory_management/c3_structs_lt_elision/Cargo.toml
       cargo run --manifest-path bootcamp/2_intermediate/2_memory_management/c4_box_smart_pointer/Cargo.toml
       cargo run --manifest-path bootcamp/2_intermediate/2_memory_management/c5_rc_smart_pointer/Cargo.toml
       cargo run --manifest-path bootcamp/2_intermediate/2_memory_management/c6_refcell_smart_pointer/Cargo.toml
       cargo run --manifest-path bootcamp/2_intermediate/2_memory_management/c7_deref_coercion/Cargo.toml
  intermediate_s3:
    name: Intermediate > 3. Understanding Error Handling
    runs-on: ubuntu-latest
    needs: intermediate_s2
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo run --manifest-path bootcamp/2_intermediate/3_error_handling/c1_unrecoverable_errors/Cargo.toml
       cargo run --manifest-path bootcamp/2_intermediate/3_error_handling/c2_recoverable_errors/Cargo.toml
       cargo run --manifest-path bootcamp/2_intermediate/3_error_handling/c3_propagating_errors/Cargo.toml
       cargo run --manifest-path bootcamp/2_intermediate/3_error_handling/c4_result_and_option/Cargo.toml
       cargo run --manifest-path bootcamp/2_intermediate/3_error_handling/c5_multiple_error_types/Cargo.toml
  intermediate_s4:
    name: Intermediate > 4. Advanced Error Handling
    runs-on: ubuntu-latest
    needs: intermediate_s3
    steps:
    - uses: actions/checkout@v4
    - name: cargo run
      run: |
       cargo run --manifest-path bootcamp/2_intermediate/4_advanced_error_handling/c1_overview/Cargo.toml